# Generated by Django 5.2.3 on 2025-06-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('oxygen_consumption', models.FloatField(default=0.5)),
            ],
        ),
        migrations.CreateModel(
            name='OxygenSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.FloatField(default=100.0)),
                ('prodution_rate', models.FloatField(default=2.0)),
                ('status', models.CharField(default='Online', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShipStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('oxygen_level', models.FloatField()),
                ('crew_count', models.IntegerField()),
                ('alert', models.TextField(blank=True)),
            ],
        ),
    ]
