# Generated by Django 5.2.3 on 2025-06-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewmember',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('MIA', 'Missing in Action'), ('KIA', 'Killed in Action')], default='ACTIVE', max_length=10),
        ),
    ]
